### ISSUE TITLE
Does not reconnect after factorio server restart (500 Server Error)

### ISSUE THREAD

**Issue by Kariton** [nekomeowww/factorio-rcon-api#17]
Hey,

the api service does not reestablish the rcon connection after a factorio server restart.
```
[Fx] HOOK OnStart		github.com/nekomeowww/factorio-rcon-api/v2/internal/grpc/servers.Modules.NewGatewayServer.func2.2() called by github.com/nekomeowww/factorio-rcon-api/v2/internal/grpc/servers.Modules.NewGatewayServer.func2 ran successfully in 383.852µs
[Fx] RUNNING
2024-12-07T08:42:04.743064559Z [error] [/app/api-server/internal/grpc/servers/interceptors/error_handler.go:50] unimplemented error error="rpc error: code = NotFound desc = Not Found"
2024-12-07T08:54:44.813992829Z [error] [/app/api-server/internal/grpc/servers/interceptors/error_handler.go:42] internal error error="rpc error: code = Internal desc = write tcp 10.41.5.75:56668->10.42.158.129:30100: write: connection timed out" file="/app/api-server/internal/grpc/services/factorioapi/v2/console/console.go:482" function="github.com/nekomeowww/factorio-rcon-api/v2/internal/grpc/services/factorioapi/v2/console.(*ConsoleService).CommandPlayers"
```

the liveness probe does also continues to think everything is okay.

in a _best case_ the liveness probe will not succeed and the service would retry to connect on its own.
depending on the configuration kubernetes would restart the pod after a few failures.

```yaml
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 24180
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
```

in my case the api container would be terminated after 30 seconds when the livenessprobe indicates an issue.
or it would reconnect within that time and everything is okay.

but nether happens and the api is stuck with `500 Server Error`

**Comment by nekomeowww** [comment]
Thanks for reporting, let me reproduce it on my side, the code might not be correctly implemented.

**Comment by Kariton** [comment]
dont know how those scenarios differ - but here is a different log:
```
2024-12-08T21:15:01.630170461Z [error] [/app/api-server/internal/grpc/servers/interceptors/error_handler.go:42] internal error error="rpc error: code = Internal desc = write tcp 10.41.5.75:56668->10.42.158.129:30100: write: broken pipe" file="/app/api-server/internal/grpc/services/factorioapi/v2/console/console.go:482" function="github.com/nekomeowww/factorio-rcon-api/v2/internal/grpc/services/factorioapi/v2/console.(*ConsoleService).CommandPlayers"
```

also after restarting the factorio server - but this time i have looked at the api log way later and not right after the server restarted.
both logs are the result of the same triggered command.

**Comment by Kariton** [comment]
were you able to reproduce this issue?

i utilize the API to figure out if someone is online and `rollout restart` the factorio-server deployment to apply mod updates on a schedule. after restarting the server the script stops working because the api keeps failing.
(api is its own deployment)

need to handle that manually for now.

**Comment by nekomeowww** [comment]
Will be fixed in https://github.com/nekomeowww/factorio-rcon-api/pull/19

**Comment by nekomeowww** [comment]
Sorry for the late reply, I was too rush and busy recent days. And finally got a day to work on side projects.

**Comment by Kariton** [comment]
@nekomeowww Hey,
even though i have updated my deployment i still cannot use the api after restarting the factorio server.
```
2024-12-26T19:16:59.090181345Z [error] [/app/api-server/internal/grpc/servers/interceptors/error_handler.go:42] internal error error="rpc error: code = Internal desc = write tcp 10.41.5.103:60752->10.42.186.189:30100: write: broken pipe" file="/app/api-server/internal/grpc/services/factorioapi/v2/console/console.go:482" function="github.com/nekomeowww/factorio-rcon-api/v2/internal/grpc/services/factorioapi/v2/console.(*ConsoleService).CommandPlayers"
```

here are some details:
cronjob to trigger rollout restart.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: factorio-rollout-restart
  namespace: factorio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: factorio-rollout-restart-role
  namespace: factorio
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: factorio-rollout-restart-rolebinding
  namespace: factorio
subjects:
  - kind: ServiceAccount
    name: factorio-rollout-restart
    namespace: factorio
roleRef:
  kind: Role
  name: factorio-rollout-restart-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: factorio-rollout-restart
  namespace: factorio
spec:
  schedule: "*/15 * * * *"
  suspend: true
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          serviceAccountName: factorio-rollout-restart
          containers:
            - name: factorio-rollout-restart
              image: REGISTRY/library/factorio-rollout-restart:1.0.0
              imagePullPolicy: Always
              securityContext:
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                runAsUser: 1001
                capabilities:
                  drop:
                    - ALL
              resources:
                limits:
                  memory: "128Mi"
                  cpu: "200m"
                requests:
                  memory: "64Mi"
                  cpu: "100m"
          restartPolicy: OnFailure
```
 
 factorio-rollout-restart Dockerfile:
 ```Dockerfile
FROM docker.io/library/python:3.13-alpine3.21@sha256:657dbdb20479a6523b46c06114c8fec7db448232f956a429d3cc0606d30c1b59

RUN apk add --no-cache curl \
        && apk add --no-cache --virtual .build-deps gcc libffi-dev musl-dev python3-dev \
        && pip install --no-cache-dir --upgrade pip

RUN addgroup --gid 1001 appuser \
        && adduser --uid 1001 --ingroup appuser --home /app --shell /sbin/nologin --disabled-password appuser \
        && chown --recursive appuser:appuser /app

WORKDIR /app

COPY src/requirements.txt /app/requirements.txt
COPY src/rollout_restart.py /app/rollout_restart.py

RUN pip install --no-cache-dir --requirement /app/requirements.txt \
        && apk del .build-deps

USER appuser

ENTRYPOINT ["python", "rollout_restart.py"]
 ```
 
 requirements.txt
 ```
kubernetes
requests
```

rollout_restart.py
```py
#!/usr/bin/env python

"""
This script restarts Factorio server deployments in a Kubernetes cluster.
It checks the online status of players via the rcon-API
and restarts the server's deployment if no players are online
and the pod has exceeded a specified age threshold.
"""

import os
import argparse
import json
import logging
import sys
from datetime import datetime, timedelta, timezone
import requests
from kubernetes import client, config


def parse_options():
    """
    Parse command-line arguments and environment variables.

    Returns:
        argparse: The parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Restart Factorio server deployments."
    )
    parser.add_argument(
        "--namespace",
        default=os.getenv("NAMESPACE", "factorio"),
        help="Kubernetes namespace",
    )
    parser.add_argument(
        "--deployment",
        default=os.getenv("DEPLOYMENT", "factorio-server"),
        help="Kubernetes deployment name",
    )
    parser.add_argument(
        "--app",
        default=os.getenv("APP", "factorio-server"),
        help="Kubernetes app name",
    )
    parser.add_argument(
        "--threshold",
        type=int,
        default=int(os.getenv("THRESHOLD", "4")),
        help="Age threshold in hours for restarting the pod",
    )
    parser.add_argument(
        "--api-url",
        default=os.getenv(
            "API_URL", "http://factorio-rcon-api.factorio:30110"
        ),
        help="Base API URL for checking player status",
    )
    parser.add_argument(
        "--debug",
        type=bool,
        default=os.getenv("DEBUG", "False").lower() in ["true", "1"],
        help="Enable debug mode for verbose logging",
    )
    return parser.parse_args()


def setup_logging(debug):
    """
    Set up logging configuration.

    Args:
        debug (bool): If True, set logging level to DEBUG, otherwise INFO.
    """
    level = logging.DEBUG if debug else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )


def is_anyone_online(api_url):
    """
    Check if any player is online via the Factorio API.

    Args:
        api_url (str): The base URL for the Factorio API.

    Returns:
        bool: True if any player is online, False otherwise.
        dict: The response data from the API.
    """
    try:
        logging.debug(
            "Sending request to %s/api/v2/factorio/console/command/players",
            api_url,
        )
        response = requests.get(
            f"{api_url}/api/v2/factorio/console/command/players", timeout=30
        )
        response.raise_for_status()
        data = response.json()

        for player in data.get("players", []):
            if player["online"]:
                return True, data
        return False, data
    except requests.RequestException as e:
        logging.error("Error checking player status: %s", e)
        logging.debug("Detailed traceback:", exc_info=True)
        sys.exit(1)


def check_container_age_and_restart_if_needed(
    namespace, app, deployment, threshold
):
    """
    Check the age of the container and restart it if necessary.

    Args:
        namespace (str): The Kubernetes namespace.
        app (str): The Kubernetes app name.
        deployment (str): The deployment name.
        threshold (int): The age threshold (in hours) for restarting the pod.
    """
    try:
        config.load_incluster_config()
        v1 = client.CoreV1Api()
        apps_v1 = client.AppsV1Api()

        label_selector = (
            f"app.kubernetes.io/name={app}" if app else f"app={deployment}"
        )
        logging.debug(
            "Fetching pods in namespace %s with label: %s",
            namespace,
            label_selector,
        )
        pods = v1.list_namespaced_pod(namespace, label_selector=label_selector)

        if not pods.items:
            logging.warning(
                "No pods found for deployment %s in namespace %s.",
                deployment,
                namespace,
            )
            return

        pod = pods.items[0]
        start_time = pod.status.start_time

        if not start_time:
            logging.warning("Failed to retrieve pod start time.")
            return

        current_time = datetime.now(timezone.utc)
        age = current_time - start_time

        if age > timedelta(hours=threshold):
            logging.info(
                "Pod is older than %d hours (Age: %s). "
                "Triggering a rollout restart...",
                threshold,
                age,
            )
            apps_v1.patch_namespaced_deployment(
                name=deployment,
                namespace=namespace,
                body={
                    "spec": {
                        "template": {
                            "metadata": {
                                "annotations": {
                                    "rollout-restarted-at": datetime.now(
                                        timezone.utc
                                    ).isoformat()
                                }
                            }
                        }
                    }
                },
            )
            logging.info("Rollout restart triggered successfully.")
        else:
            logging.info(
                "Pod age is %s, which is within the acceptable limit "
                "(less than %d hours).",
                age,
                threshold,
            )

    except client.exceptions.ApiException as e:
        logging.error("Error interacting with Kubernetes API: %s", e)
        logging.debug("Detailed traceback:", exc_info=True)
        sys.exit(1)


def main():
    """
    Main function rollout restart the Factorio server Kubernetes deployment.
    """
    options = parse_options()
    setup_logging(options.debug)

    logging.info("Starting Factorio server rollout restart script...")

    online_status, data = is_anyone_online(options.api_url)

    if online_status:
        logging.info("Players online.")
        logging.debug(json.dumps(data, indent=4))
    else:
        logging.info("No players online. Checking container deployment age...")
        check_container_age_and_restart_if_needed(
            options.namespace,
            options.app,
            options.deployment,
            options.threshold,
        )


if __name__ == "__main__":
    main()
```

feel free to include this as usage example or whatever. ;)
