### ISSUE TITLE
Cannot get banlist after ban via API

### ISSUE THREAD

**Issue by bluedotiya** [nekomeowww/factorio-rcon-api#20]
Hello,

First of all thank for sharing this cool rcon API with the community,
I recently encounter a behavior i believe is a bug:

**Bug description:**
After banning a player via the API, further reqeust to get the server ban list fails

**Steps to reproduce:**
1. Ban a player via the API endpoint - POST api/v2/factorio/console/command/ban
2. Fetch the current banned player list with GET /api/v2/factorio/console/command/bans
3. Server return 400 - BAD REQUEST 
**details: "failed to parse admins: Banned players: player_x, player_y, player_z and user due to parts not equals 2"**
**From the RCON-API container there seems to be no error at the time of the 400 HTTP Error nor at the factorio server**

**Code snippet i try to run against the API server (fails at requests.get)**
```
    def get_ban_list(self):
        response = requests.get(f"http://{self.api_server_address}/api/v2/factorio/console/command/bans")
        banned_players = response.json()
        
        return banned_players
```

**Env details:**
Container runtime: containerd
Image version: ghcr.io/nekomeowww/factorio-rcon-api:2.0.3
Lang: Python via requests

**Docker Compose factorio-rcon-api yaml:**
```
factorio-rcon-api:
    image: ghcr.io/nekomeowww/factorio-rcon-api:2.0.3
    pull_policy: always
    container_name: factorio-rcon-api
    depends_on:
      factorio:
        condition: service_healthy
    environment:
      - FACTORIO_RCON_HOST=copperhead.local
      - FACTORIO_RCON_PORT=27015
    volumes:
      - /opt/factorio/config/rconpw:/run/secrets/rconpw:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      sh -c "export FACTORIO_RCON_PASSWORD=$(cat /run/secrets/rconpw) &&
      /usr/local/bin/factorio-rcon-api"
    ports:
      - 24180:24180
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:24180/api/v2/factorio/console/command/version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: loki
      options:
        loki-url: "http://copperhead.local:3100/loki/api/v1/push"
```
Would gladly assist in solving this as best as i can :)

Thanks,
Oran
